### ISSUE TITLE
had trouble building Chapter02

### ISSUE THREAD

**Issue by cavapoo2** [PacktPublishing/Cloud-Native-programming-with-Golang#2]
in order to install packages and build the main, i had to edit some of the source files paths. I changed "chaper02" to "Chapter02", i.e from lowercase c to uppercase. 
for example in mongolayer.go
i changed 
"github.com/PacktPublishing/Cloud-Native-programming-with-Golang/chapter02/myevents/src/lib/persistence"
 
to this

"github.com/PacktPublishing/Cloud-Native-programming-with-Golang/Chapter02/myevents/src/lib/persistence"

**Comment by rathishubham7** [comment]
Have experienced similar issues.
